export const footballMatchesText = {
    footballMatches: { en: "Football Matches", lb: "مباريات كرة قدم" },
    nowPlaying: { en: "Now Playing", lb: "جاري التشغيل" },
    argentina: { en: "Argentina", lb: "الأرجنتين" },
    brazil: { en: "Brazil", lb: "البرازيل" },
    one: { en: "1", lb: "١" },
    zero: { en: "0", lb: "٠" },
    groupA: { en: "group A", lb: "الفرقة الأولي" },
    michiganStadium: { en: "Michigan Stadium", lb: "ملعب ميشيغان" },
    denmark: { en: "Denmark", lb: "الدنمارك" },
    france: { en: "France", lb: "فرنسا" },
    groupB: { en: "group B", lb: "الفرقة الثانية" },
    fnbStadium: { en: "FNB Stadium", lb: "ملعب FNB" },
    japan: { en: "Japan", lb: "اليابان" },
    russia: { en: "Russia", lb: "روسيا" },
    two: { en: "2", lb: "٢" },
    firstStadium: { en: "First Stadium", lb: "الملعب الأول" },
    uruguay: { en: "Uruguay", lb: "أوروغواي" },
    portugal: { en: "Portugal", lb: "البرتغال" },
    uruguayVsportugal : { en : "Uruguay vs Portugal", lb : "أوروغواي  البرتغال "},
    london: { en: "London", lb: "لندن" },
    dayleft1: { en: "1 Day left", lb: "باقي يوم واحد" },
    URU: { en: "URU", lb: "أوروغواي" },
    POR: { en: "POR", lb: "البرتغال" },
    wembleyStadium: { en: "Wembley Stadium", lb: "ملعب ويمبلي" },
    franceVsArgentina: { en: "France vs Argentina", lb: "فرنسا ضد الأرجنتين" },
    FRA: { en: "FRA", lb: "فرنسا" },
    ARG: { en: "ARG", lb: "الأرجنتين" },
    daysLeft2: { en: "2 Days Left", lb: "باقي يومان" },
    russiaSochi: { en: "Russia, Sochi", lb: "روسيا، سوتشي" },
    brazilVsEngland: { en: "Brazil vs England", lb: "البرازيل ضد إنجلترا" },
    pasadena: { en: "Pasadena", lb: "باسادينا" },
    BRA : { en: "BRA", lb: "البرازيل" },
    ENG: { en: "ENG", lb: "إنجلترا" },
    daysLeft3: { en: "3 days left", lb: "باقي ثلاث أيام" },
    daysLeft4: { en: "4 days left", lb: "باقي ثلاث أيام" },
    roseBowl: { en: "ROSE BOWL", lb: "ملعب روز بول" },
    russiaVsSweden: { en: "RUSSIA vs Sweden", lb: "روسيا ضد السويد" },
    RUS : { en :"RUS", lb : "روسيا"},
    SWE: { en: "SWE", lb: "السويد" },
    eastRutherford: { en: "East Rutherford", lb: "شرق راذرفورد" },
    metlifeStadium: { en: "Metlife Stadium", lb: "ملعب ميتلايف" },
    date1: { en: "18/02/2021", lb: "١٨/٠٢/٢٠٢١" },
    date2: { en: "20/02/2021", lb: "٢٠/٠٢/٢٠٢١" },
    date3: { en: "21/02/2021", lb: "٢١/٠٢/٢٠٢١" },
    date4: { en: "22/02/2021", lb: "٢٢/٠٢/٢٠٢١" },
    matchesUpdate : {en : "Matches Update", lb : 'تحديث المباريات'},
    famousPlayers : { en :"Famous Players", lb : "مشاهير اللاعبين"},
    footballHistory  : { en :"Football History", lb : "تاريخ كرة القدم"},

    famousFootballPlayer: { en: "Famous Football Players", lb: "لاعبي كرة القدم المشهورين" },
    lionelMessi: { en: "Lionel Messi", lb: "ليونيل ميسي" },
    FCBarcelona: { en: "FC Barcelona", lb: "نادي برشلونة" },
    cristianoRonaldo: { en: "Cristiano Ronaldo", lb: "كريستيانو رونالدو" },
    juvetusFC: { en: "Juvetus F.C", lb: "نادي يوفنتوس" },
    mohammedSalah: { en: "Mohammed Salah", lb: "محمد صلاح" },
    liverpoolFC: { en: "Liverpool FC", lb: "نادي ليفربول" },
    neymar: { en: "Neymar", lb: "نيمار" },
    psg: { en: "Paris Saint-Germain F.C", lb: "كيليان مبابي" },
    kylianMbappe: { en: "Kylian Mbappe", lb: "كيليان مبابي" },
    robertLewandovski: { en: "Robert Lewandovski", lb: "روبرت ليفاندوفسكي" },
    FCBayernMunich: { en: "FC Bayern Munich", lb: "نادي بايرن ميونخ" },
    karimBenzema: { en: "Karim Benzema", lb: "كريم بنزيما" },
    realMadrid: { en: "Real Madrid", lb: "ريال مدريد" },
    kevinDeBruyne: { en: "Kevin De Bruyne", lb: "كيفين دي بروين" },
    manchesterCityFC: { en: "Manchester City FC", lb: "نادي مانشستر سيتي" },

  };